- name: Ensure common packages are installed
  apt:
    name:
      - git
      - curl
      - vim
    state: present

- name: Copy configuration file from template
  template:
    src: example.j2
    dest: /etc/example.conf

- name: Start and enable example service
  service:
    name: example
    state: started
    enabled: yes